spring:
  security:
    user:
      name: admin
      password: admin
  freemarker:
    prefix:
    content-type: text/html
    enabled: true
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    charset: UTF-8

logging:
  level:
    com.app: debug
    org.springframework.security.web.authentication.logout: debug

